# Controls when the action will run. 
on:
  push:
    branches:
      - pdf
      - main
    paths:
      - 'LaTeX/**'
  pull_request:
      branches: [ pdf ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install texlive and related fonts
        run:
          sudo apt install -y texlive texlive-xetex texlive-lang-chinese gsfonts fonts-moe-standard-kai ttf-mscorefonts-installer librsvg2-bin texlive-fonts-extra 
      - name: Test LaTeX
        working-directory: ./latex
        run: |
          xelatex report.tex
          xelatex report.tex
          xelatex report.tex

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.test2 }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.test2 }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./latex/report.pdf
          asset_name: report.pdf
          asset_content_type: pdf
